---
- name: Overwrite Oracle the docker-compose
  hosts: oracle
  become: true
  tasks:
  - name: stop the service
    shell: service poabridge stop

  - include_tasks: oracle-add-docker-external-network.yml
    with_items:
      - docker-compose
      - docker-compose-transfer
      - docker-compose-erc-native

  - name: start the service
    shell: service poabridge start
